logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#spring:
#  redis:
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.150.101:27001
#        - 192.168.150.101:27002
#        - 192.168.150.101:27003